name: pexels_client
description: An unofficial dart wrapper for the [Pexels API](https://www.pexels.com/api/).
version: 2.1.0
repository: https://github.com/MarkIvanDev/pexels_client

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.3.0
  json_annotation: ^4.9.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
  build_runner: ^2.4.15
  json_serializable: ^6.9.0
  envied: ^0.5.4+1
  envied_generator: ^0.5.4+1
