name: pexels_client
description: An unofficial dart wrapper for the [Pexels API](https://www.pexels.com/api/).
version: 1.0.0
repository: https://github.com/MarkIvanDev/pexels_client

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.2.0
  json_annotation: ^4.8.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.8
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  envied: ^0.5.3
  envied_generator: ^0.5.3
